### ISSUE TITLE
Cannot find module './lib/proxy'

### ISSUE THREAD

**Issue by hanxzi** [xiaohuoni/antd-pro-server#1]
[nodemon] watching: *.*
[nodemon] starting `node app.js`
module.js:549
    throw err;
    ^

Error: Cannot find module './lib/proxy'
    at Function.Module._resolveFilename (module.js:547:15)
    at Function.Module._load (module.js:474:25)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/Users/hanxzi/Documents/code/antd-pro-server/app.js:3:17)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
[nodemon] app crashed - waiting for file changes before starting...

**Comment by jasp402** [comment]
It is corrected by changing the path

> app.js
`var {resData} = require("./mock/proxy");`

**Comment by xiaohuoni** [comment]
https://github.com/xiaohuoni/antd-pro-server/blob/6b8a746cf7eceae31af002ae87f2c3d1ea1e0c26/app.js#L3
